nodeLinker: node-modules
enableGlobalCache: true

packageExtensions:
  "@inversifyjs/core@*":
    peerDependencies:
      reflect-metadata: "*"
    peerDependenciesMeta:
      reflect-metadata:
        optional: false

pnpIgnorePatterns:
  - "**/esbuild/**"
  - "**/@rollup/**"
