services:
  glspgen:
    image: glsp-generator:local
    container_name: glspgen
    ports:
      - "51620:51620"
    volumes:
      - ./packages/generator/workspace:/workspace
    command: dist/api-server.js
    environment:
      - NODE_ENV=production
      - API_PORT=51620
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:51620/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s