# Docker Compose for GLSP Generator
# This file uses the published GitHub Container Registry image
# Users can download this file and run: docker-compose up -d

version: '3.8'

services:
  glspgen:
    image: ghcr.io/johnholliday/glsp-generator:latest
    container_name: glspgen
    ports:
      - "51620:51620"
    environment:
      - NODE_ENV=production
      - API_PORT=51620
      - LOG_LEVEL=info
    volumes:
      # Mount local workspace for input/output files
      - ./workspace:/workspace
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/health', (r) => process.exit(r.statusCode === 200 ? 0 : 1))"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    command: ["node", "dist/api-server.js"]
    
  # CLI service for one-off commands
  # Usage: docker-compose run --rm cli generate /workspace/grammar.langium
  cli:
    image: johnholliday/glsp-generator:latest
    container_name: glsp-generator-cli
    volumes:
      - ./workspace:/workspace
    environment:
      - LOG_LEVEL=info
    profiles:
      - cli
    # Override with your command
    command: ["--help"]

volumes:
  workspace:
    driver: local

networks:
  default:
    name: glsp-network